# Standards: 2.1.0
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored

# 1.1.1.5 - Ensure mounting of hfsplus filesystems is disabled

- name: 1.1.1.5 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_5
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored

- name: 1.1.1.5 - Ensure mounting of hfsplus filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install hfsplus /bin/true\n"
  when: modprobe_1_1_1_5.stat.exists is not defined or not modprobe_1_1_1_5.stat.exists
  register: action_1_1_1_5_01
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored

- name: 1.1.1.5 - Ensure mounting of hfsplus filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install hfsplus"
    line: "install hfsplus /bin/true"
  when: modprobe_1_1_1_5.stat.exists is defined and modprobe_1_1_1_5.stat.exists
  register: action_1_1_1_5_02
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored

- name: 1.1.1.5 - Ensure hfsplus module is removed from kernel
  modprobe:
    name: hfsplus
    state: absent
  register: action_1_1_1_5_03
  
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored

- name: 1.1.1.5 - Logging Task 
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.1.5 : insert install hfsplus /bin/true into {{ cis_modprobe_conf_filename }}"
  when: action_1_1_1_5_01 is defined and action_1_1_1_5_01.changed  
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored

- name: 1.1.1.5 - Logging Task
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 1.1.1.5 : Create  {{ cis_modprobe_conf_filename }} with content 'install hfsplus /bin/true'"
  when: action_1_1_1_5_02 is defined and action_1_1_1_5_02.changed 
  
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored

- name: 1.1.1.5 - Logging Task
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 1.1.1.5 : 'execute hfsplus cramfs'"
  when: action_1_1_1_5_03 is defined and action_1_1_1_5_03.changed 
  
  tags:
    - level-1
    - section-1
    - "1.1.1.5"
    - scored
