# Standards: 2.1.0
---
# Include date, time and process id finder
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.1.1.6"
    - scored
  
# 1.1.1.6 - Ensure mounting of squashfs filesystems is disabled

- name: 1.1.1.6 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_6
  tags:
    - level-1
    - section-1
    - "1.1.1.6"
    - scored

- name: 1.1.1.6 - Ensure mounting of squashfs filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install squashfs /bin/true\n"
  when: modprobe_1_1_1_6.stat.exists is not defined or not modprobe_1_1_1_6.stat.exists
  register: action_1_1_1_6_01

  tags:
    - level-1
    - section-1
    - "1.1.1.6"
    - scored

- name: 1.1.1.6 - Ensure mounting of squashfs filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install squashfs"
    line: "install squashfs /bin/true"
  when: modprobe_1_1_1_6.stat.exists is defined and modprobe_1_1_1_6.stat.exists
  register: action_1_1_1_6_02
  tags:
    - level-1
    - section-1
    - "1.1.1.6"
    - scored

- name: 1.1.1.6 - Ensure squashfs module is removed from kernel
  modprobe:
    name: squashfs
    state: absent
  register: action_1_1_1_6_03

  tags:
    - level-1
    - section-1
    - "1.1.1.6"
    - scored
  
- name: 1.1.1.6 - Logging Task 
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.1.6 : insert install squashfs /bin/true into {{ cis_modprobe_conf_filename }}"
  when: action_1_1_1_6_01 is defined and action_1_1_1_6_01.changed

  tags:
    - level-1
    - section-1
    - "1.1.1.6"
    - scored

- name: 1.1.1.6 - Logging Task 
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.1.6 : Append install squashfs /bin/true into {{ cis_modprobe_conf_filename }}"
  when: action_1_1_1_6_02 is defined and action_1_1_1_6_02.changed

  tags:
    - level-1
    - section-1
    - "1.1.1.6"
    - scored

- name: 1.1.1.6 - Logging Task 
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 1.1.1.6 : 'execute rmmod squashfs'"
  when: action_1_1_1_6_03 is defined and action_1_1_1_6_03.changed

  tags:
    - level-1
    - section-1
    - "1.1.1.6"
    - scored