---
# Standards: 2.1.0
# Include date, time and process id finder
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

# 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled
- name: 1.1.1.1 - Check if CIS modprobe configuration file exists
  stat:
    path: "{{ cis_modprobe_conf_filename }}"
  register: modprobe_1_1_1_1
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

- name: 1.1.1.1 - Display CIS modprobe file
  debug:
    msg: CIS modprobe file - {{ modprobe_1_1_1_1.stat.path }}
  when: modprobe_1_1_1_1.stat.exists is defined and modprobe_1_1_1_1.stat.exists
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

- name: 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled
  copy:
    dest: "{{ cis_modprobe_conf_filename }}"
    content: "install cramfs /bin/true\n"
  when: modprobe_1_1_1_1.stat.exists is not defined or not modprobe_1_1_1_1.stat.exists
  register: action_1_1_1_1_01
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

- name: 1.1.1.1 - Ensure mounting of cramfs filesystems is disabled
  lineinfile:
    dest: "{{ cis_modprobe_conf_filename }}"
    regexp: "^install cramfs"
    line: "install cramfs /bin/true"
  when: modprobe_1_1_1_1.stat.exists is defined and modprobe_1_1_1_1.stat.exists
  register: action_1_1_1_1_02

  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

- name: 1.1.1.1 - Ensure cramfs module is removed from kernel
  modprobe:
    name: cramfs
    state: absent
  register: action_1_1_1_1_03
  
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

- name: 1.1.1.1 - Logging Task 
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.1.1 : insert install cramfs /bin/true into {{ cis_modprobe_conf_filename }}"
  when: action_1_1_1_1_01 is defined and action_1_1_1_1_01.changed  
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

- name: 1.1.1.1 - Logging Task
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.1.1.1 : Create  {{ cis_modprobe_conf_filename }} with content 'install cramfs /bin/true'"
  when: action_1_1_1_1_02 is defined and action_1_1_1_1_02.changed 
  
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

- name: 1.1.1.1 - Logging Task
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} 1.1.1.1 : 'execute rmmod cramfs'"
  when: action_1_1_1_1_03 is defined and action_1_1_1_1_03.changed 
  
  tags:
    - level-1
    - section-1
    - "1.1.1.1"
    - scored

