# Standards: 0.11
---

# 1.5.3 Ensure address space layout randomization (ASLR) is enabled
# For more information please check below Oracle Document link 
# https://docs.oracle.com/en/operating-systems/oracle-linux/8/security/ol-aslr-sec.html#treeDiv

- name: 1.5.3 - Ensure address space layout randomization is enabled
  sysctl:
    ignoreerrors: yes
    name: kernel.randomize_va_space
    value: 2
    state: present
  tags:
    - level-1
    - "1.5.3"
    - scored
