# Standards: 2.1.0
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "1.5.4"
    - scored
  
# 1.5.4 Ensure prelink is disabled

- name: 1.5.4 - Check if prelink binary exists
  yum:
    list: prelink
  register: which_1_5_4
  tags:
    - level-1
    - "1.5.4"
    - scored
    - skip_ansible_lint

- name: 1.5.4 - Display registered output
  debug:
    msg: Ouput message is {{ which_1_5_4 }}
  tags:
    - level-1
    - "1.5.4"
    - scored
    - skip_ansible_lint

- name: 1.5.4 - Restore prelinked binaries
  command: prelink -ua
  when: "'installed' in which_1_5_4.results"
  register: action_1_5_4_01

  tags:
    - level-1
    - "1.5.4"
    - scored
    - skip_ansible_lint

- name: 1.5.4 - Ensure prelink is disabled
  yum:
    name: prelink
    state: absent
  register: action_1_5_4_02
  tags:
    - level-1
    - "1.5.4"
    - scored

- name: 1.5.4 - Logging action uninstall prelink binary
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 1.5.4 : Execute 'prelink -ua and yum remove prelink'"
  when: action_1_5_4_01 is defined and action_1_5_4_01.changed
  
  tags:
    - level-1
    - "1.5.4"
    - scored
  
  
  
