# Standards: 2.1.0
---

- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "3.1.2"
    - scored

# 3.1.2 Ensure packet redirect sending is disabled 

- name: 3.1.2 - Ensure packet redirect sending is disabled and updated in the active kernel too
  sysctl:
    name: "{{ item }}"
    ignoreerrors: yes
    value: '0'
    sysctl_set: yes
    state: present
    reload: yes
  with_items: "{{ cis_3_1_2_files }}"
  register: action_3_1_2
  notify: Flush ipv4 route
  tags:
    - level-1
    - section-3
    - "3.1.2"
    - scored

- name: 3.1.2 - Logging action 'Ensure packet redirect sending is disabled and updated in the active kernel too'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 3.1.2 : Execute 'sysctl -w {{ item }} = 0'"
    with_item: "{{ cis_3_1_2_files }}"
  when: action_3_1_2 is defined and action_3_1_2.changed
  tags:
    - level-1
    - "3.1.2"
    - scored