# Standards: 2.1.0
---

# 3.6.1 Ensure firewalld is installed
# NOTE REPLACED IPTABLES WITH FIREWALLD
# Include date, time and process id finder
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "3.6.1"
    - scored
  
- name: 3.6.1 - Ensure firewalld is installed
  yum:
    name: "{{ cis_firewalld_install.package }}"
    state: "{{ cis_firewalld_install.state }}"
  with_items:
    - "{{ cis_firewalld_install }}"
  when: cis_firewalld_install.state == "present"
  register: action_3_6_1
  tags:
    - level-1
    - section-3
    - "3.6.1"
    - scored

- name: 3.6.1 - Ensure firewalld is started
  service:
    name: "{{ cis_firewalld_install.service }}"
    enabled: "{{ cis_firewalld_install.enabled }}"
    state: "{{ cis_firewalld_install.rstate }}"
  with_items:
    - "{{ cis_firewalld_install }}"
  when: cis_firewalld_install.state == "present"
  tags:
   - level-1
   - section-3
   - "3.6.1"
   - scored

- name: 3.6.1 - Logging Task 'Ensure iptables is installed'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 3.6.1 : 'yum install iptables/firewald'"
  when: action_3_6_1 is defined and action_3_6_1.changed 
  tags:
    - level-1
    - section-1
    - "3.6.1"
    - scored