# Standards: 2.1.0
---

# 5.1.2 Ensure permissions on /etc/crontab are configured
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.1.2"
    - scored

- name: 5.1.2 - Ensure permissions on /etc/crontab are configured
  file:
    path: "/etc/crontab"
    owner: root
    group: root
    mode: '0600'
  register: action_5_1_2
  tags:
    - level-1
    - section-5
    - "5.1.2"
    - scored

- name: 5.1.2 - Logging Task 'Ensure cron daemon is enabled'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.1.2 : chown root:root /etc/crontab && chmod og-rwx /etc/crontab"
  when: action_5_1_2 is defined and action_5_1_2.changed 
  tags:
    - level-1
    - section-1
    - "5.1.2"
    - scored