# Standards: 2.1.0
---

# 5.2.4 - Ensure SSH X11 forwarding is disabled
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "5.2.4"
    - scored
  
- include: stat_sshd_config.yml
  tags:
    - level-1
    - section-5
    - "5.2.4"
    - scored

- name: 5.2.4 - Ensure SSH X11 forwarding is disabled
  lineinfile:
    regexp: "^X11Forwarding\\s+"
    backup: yes
    line: "X11Forwarding no"
    insertbefore: "^#*X11Forwarding"
    dest: "/etc/ssh/sshd_config"
  when: sshd_config.stat.exists
  register: action_5_2_4
  notify:
    - Restart sshd
  tags:
    - level-1
    - section-5
    - "5.2.4"
    - scored


- name: 5.2.4 - Logging Task 'Ensure SSH X11 forwarding is disabled'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }} : 5.2.4 : 'X11Forwarding no' -> /etc/ssh/sshd_config"
  when: action_5_2_4 is defined and action_5_2_4.changed 
  tags:
    - level-1
    - section-1
    - "5.2.4"
    - scored
