# Standards: 2.1.0
---
- include: facts/date_time_pid.yml
  tags:
    - level-1
    - section-1
    - "6.2.5"
    - scored

# 6.2.5 Ensure root is the only UID 0 account

- name: 6.2.5 - Ensure root is the only UID 0 account
  shell: "cat /etc/passwd | awk -F: '($3 == 0) { print $1 }'"
  check_mode: no
  changed_when: False
  register: cat_6_2_5
  tags:
    - level-1
    - section-6
    - "6.2.5"
    - scored

- name: 6.2.5 - Warn if root is not the only UID 0 account
  debug:
    msg: "*** ACTION REQUIRED *** root is not the only UID 0 account"
  when:
    - cat_6_2_5.stdout_lines is defined and (cat_6_2_5.stdout_lines|length > 1 or (cat_6_2_5.stdout_lines|length == 1 and 'root' not in cat_6_2_5.stdout_lines))
  tags:
    - level-1
    - section-6
    - "6.2.5"
    - scored

- name: '6.2.5 - Logging action - Ensure root is the only UID 0 account'
  lineinfile:
    path: "{{ cis_hot_fix_ansible_log }}"
    create: yes
    line: "{{ date_time }} : {{ process_id }}: 6.2.5 : *** ACTION REQUIRED *** root is not the only UID 0 account"
  when: - cat_6_2_5.stdout_lines is defined and (cat_6_2_5.stdout_lines|length > 1 or (cat_6_2_5.stdout_lines|length == 1 and 'root' not in cat_6_2_5.stdout_lines))
  
  tags:
    - level-1
    - "6.2.5"
    - scored