# Standards: 0.11
---

- include: "level-1/1.1.1.1.yml"
- include: "level-1/1.1.1.2.yml"
- include: "level-1/1.1.1.3.yml"
- include: "level-1/1.1.1.4.yml"
- include: "level-1/1.1.1.5.yml"
- include: "level-1/1.1.1.6.yml"
- include: "level-1/1.1.1.7.yml"
- include: "level-1/1.1.1.8.yml"
  when: cis_apply_on_oci is defined and cis_apply_on_oci == True
- include: "level-1/1.1.14.yml"
- include: "level-1/1.1.15.yml"
- include: "level-1/1.1.16.yml"
- include: "level-1/1.1.17.yml"
- include: "level-1/1.1.3.yml"
- include: "level-1/1.1.4.yml"
- include: "level-1/1.2.3.yml"
- include: "level-1/1.3.1.yml"
- include: "level-1/1.3.2.yml"
- include: "level-1/1.4.1.yml"
- include: "level-1/1.4.3.yml"
- include: "level-1/1.5.1.yml"
- include: "level-1/1.5.3.yml"
- include: "level-1/1.5.4.yml"
- include: "level-1/1.7.1.5.yml"
- include: "level-1/2.2.19.yml"
- include: "level-1/2.3.1.yml"
- include: "level-1/2.3.2.yml"
- include: "level-1/2.3.3.yml"
- include: "level-1/2.3.4.yml"
- include: "level-1/2.3.5.yml"
- include: "level-1/3.1.1.yml"
- include: "level-1/3.1.2.yml"
- include: "level-1/3.2.1.yml"
- include: "level-1/3.2.2.yml"
- include: "level-1/3.2.3.yml"
- include: "level-1/3.2.4.yml"
- include: "level-1/3.2.5.yml"
- include: "level-1/3.2.6.yml"
- include: "level-1/3.2.7.yml"
- include: "level-1/3.2.8.yml"
- include: "level-1/3.4.1.yml"
- include: "level-1/3.4.4.yml"
- include: "level-1/3.4.5.yml"
- include: "level-1/3.6.1.yml"
- include: "level-1/4.2.1.3.yml"
- include: "level-1/5.1.1.yml"
- include: "level-1/5.1.2.yml"
- include: "level-1/5.1.3.yml"
- include: "level-1/5.1.4.yml"
- include: "level-1/5.1.5.yml"
- include: "level-1/5.1.6.yml"
- include: "level-1/5.1.7.yml"
- include: "level-1/5.2.1.yml"
- include: "level-1/5.4.3.yml"
- include: "level-1/6.1.2.yml"
- include: "level-1/6.1.3.yml"
- include: "level-1/6.1.4.yml"
- include: "level-1/6.1.5.yml"
- include: "level-1/6.1.6.yml"
- include: "level-1/6.1.7.yml"
- include: "level-1/6.1.8.yml"
- include: "level-1/6.1.9.yml"
- include: "level-1/6.2.15.yml"
- include: "level-1/6.2.3.yml"
- include: "level-1/6.2.4.yml"
- include: "level-1/6.2.5.yml"
- include: "level-1/6.2.7.yml"